[package]
name = "generic-simd-dispatch-test"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
generic-simd = { path = "../generic-simd" }
multiversion = "0.5"
