[package]
name = "safe-simd"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"

[dependencies]
num-complex = "0.2"
safe-simd-macros = { path = "../safe-simd-macros" }
